{"name": "test_risk_users", "status": "passed", "steps": [{"name": "【风险用户总数】接口", "status": "passed", "start": 1753946651500, "stop": 1753946651521}, {"name": "首页风险用户总数和用户-用户列表总数对比一致", "status": "passed", "start": 1753946651521, "stop": 1753946651521}], "attachments": [{"name": "log", "source": "e942231c-15f9-4707-9b81-d887ad7b59e5-attachment.txt", "type": "text/plain"}], "start": 1753946651500, "stop": 1753946651522, "uuid": "19ce441b-4c02-41be-bc67-2dd4ce0357cb", "historyId": "7148a9b4c8fb9c7a213d3b0032c4aceb", "testCaseId": "7148a9b4c8fb9c7a213d3b0032c4aceb", "fullName": "test_case.test_risk_overview.test_risk_users.TestCase#test_risk_users", "labels": [{"name": "story", "value": "【风险用户总数】"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "【首页】-【风险概览】-【风险用户总数】"}, {"name": "parentSuite", "value": "test_case.test_risk_overview"}, {"name": "suite", "value": "test_risk_users"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "5CD2323XZM"}, {"name": "thread", "value": "6012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_risk_overview.test_risk_users"}], "titlePath": ["test_case", "test_risk_overview", "test_risk_users.py", "TestCase"]}